AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - bin/*

Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/IndentHash:
  EnforcedStyle: consistent

Metrics/AbcSize:
  Max: 15

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RedundantReturn:
  AllowMultipleReturnValues: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/FirstParameterIndentation:
  Enabled: false

Layout/AlignParameters:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Max: 4

Metrics/PerceivedComplexity:
  Max: 6

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Max: 100
  Exclude:
    - spec/**/*

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/SymbolArray:
  Enabled: false

Metrics/ClassLength:
  Enabled: false
