json.extract! admission,
  :id,
  :petitioner_id,
  :petitioner_name,
  :petitioner_type,
  :petitioner_phone,
  :petitioner_email,
  :patient_name,
  :species,
  :sex,
  :breed,
  :months,
  :owner_name,
  :comments,
  :created_at,
  :updated_at
json.url admission_url(admission, format: :json)
